using CheatEngine.Client.SourceGenerators.Lua.Tests.Infrastructure;

namespace CheatEngine.Client.SourceGenerators.Lua.Tests.Snapshots;

/// <summary>
///     Golden snapshot of one generated module (DoD D.8: useful, not sufficient). A formatting-only change of the emitter
///     changes this golden and, at most, the literal-text assertions of <c>ModuleContractTests</c>.
/// </summary>
/// <remarks>
///     The module holds no Lua logic: it hands its bindings' <c>TryRegisterLuaFunctions</c> to the per-assembly registrar
///     and keeps the registration lease. The registrar's decisions are proven by the EndToEnd tests, the SDK members its
///     adapter may use by <c>GeneratedLuaSurfaceRatchetTests</c>, and the public contract by <c>ModuleContractTests</c>.
/// </remarks>
public sealed class ModuleSnapshots
{
	private const string ModuleSource =
		"""
		using CheatEngine.Client.Lua;
		using CheatEngine.SDK.Annotations.Lua;
		namespace TestPlugin;
		internal static partial class PluginLuaBindings
		{
			[LuaFunction("status")]
			public static string Status() => "ok";

			[LuaFunction("ping")]
			public static int Ping() => 1;
		}

		[CheatEngineLuaModule(typeof(PluginLuaBindings), "plugin")]
		internal sealed partial class PluginLuaModule : ILuaModule;
		""";

	private const string ModuleGolden =
		"""
		// <auto-generated />
		#nullable enable

		namespace TestPlugin;

		internal partial class PluginLuaModule : global::CheatEngine.Client.Lua.ILuaModule
		{
			/// <summary>Initializes a Lua module instance for activation-scoped dependency injection.</summary>
			public PluginLuaModule()
			{
			}

			private static readonly global::CheatEngine.Client.Lua.LuaModuleDescriptor s_descriptor =
				new global::CheatEngine.Client.Lua.LuaModuleDescriptor(
					"plugin",
					global::System.Collections.Immutable.ImmutableArray.Create(new global::CheatEngine.Client.Lua.LuaExportDescriptor("status"), new global::CheatEngine.Client.Lua.LuaExportDescriptor("ping")));

			// The CheatEngine.SDK registration lease this module owns while it is registered; null otherwise. Main thread only.
			private object? _luaRegistration;

			/// <inheritdoc />
			public global::CheatEngine.Client.Lua.LuaModuleDescriptor Descriptor => s_descriptor;

			/// <inheritdoc />
			public void Register()
			{
				global::CheatEngine.Client.Lua.Generated.CheatEngineLuaModuleRegistrar.Register(s_descriptor, ref _luaRegistration,
					static state => global::TestPlugin.PluginLuaBindings.TryRegisterLuaFunctions(state,
						global::CheatEngine.SDK.Lua.Registration.LuaRegistrationCollisionPolicy.RejectExisting));
			}

			/// <inheritdoc />
			public global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome Unregister()
			{
				return global::CheatEngine.Client.Lua.Generated.CheatEngineLuaModuleRegistrar.Unregister(s_descriptor, ref _luaRegistration);
			}
		}
		""";

	[Fact]
	public void ModuleSnapshotMatchesTheRegistrationLeaseContract()
	{
		GeneratorRun run = GeneratorRun.Execute(ModuleSource);

		Assert.Empty(run.Diagnostics);
		Assert.Equal(Normalize(ModuleGolden) + "\n",
			Normalize(run.GeneratedText("PluginLuaModule.CheatEngineLuaModule.g.cs")));
	}

	[Fact]
	public void TheRegistrarAndItsSdkAdapterAreEmittedOnceWithTheirConstantText()
	{
		GeneratorRun run = GeneratorRun.Execute(ModuleSource);

		Assert.Equal(Normalize(RegistrarEmitter.RegistrarSource), Normalize(run.GeneratedText(RegistrarEmitter.RegistrarHintName)));
		Assert.Equal(Normalize(RegistrarEmitter.AdapterSource), Normalize(run.GeneratedText(RegistrarEmitter.AdapterHintName)));
		Assert.Equal(3, run.GeneratedSources.Length);
	}

	private static string Normalize(string text)
	{
		return text.Replace("\r\n", "\n", StringComparison.Ordinal);
	}
}
