using CheatEngine.Client.SourceGenerators.Lua.Tests.Infrastructure;

namespace CheatEngine.Client.SourceGenerators.Lua.Tests.Snapshots;

/// <summary>
///     Golden snapshot of one generated module (DoD D.8: useful, not sufficient). A formatting-only change of the emitter
///     changes this golden and, at most, the literal-text assertions of <c>SdkPortStackDisciplineTests</c> and
///     <c>ModuleContractTests</c>.
/// </summary>
/// <remarks>
///     This golden does not prove the SDK port struct (<c>__CheatEngineLuaSdkPort</c>): the port is the only generated code
///     that runs against the real Lua state, and the EndToEnd tests replace it with a managed double. Its decisions are
///     pinned, formatting-free, by <c>SdkPortDecisionTests</c> (C0). A port change that also changes the expected paths of
///     that test is a change of the Q16 contract of production code, not a formatting change: record it in the generator
///     README and in the ADR-01 entry of docs/migration/sdk-2.0.md. The algorithm around the port is proven by the EndToEnd
///     tests, the public contract by <c>ModuleContractTests</c>.
/// </remarks>
public sealed class ModuleSnapshots
{
	private const string ModuleSource =
		"""
		using CheatEngine.Client.Lua;
		using CheatEngine.SDK.Annotations.Lua;
		namespace TestPlugin;
		internal static partial class PluginLuaBindings
		{
			[LuaFunction("status")]
			public static string Status() => "ok";

			[LuaFunction("ping")]
			public static int Ping() => 1;
		}

		[CheatEngineLuaModule(typeof(PluginLuaBindings), "plugin")]
		internal sealed partial class PluginLuaModule : ILuaModule;
		""";

	private const string OwnershipAwareModuleGolden =
		"""
		// <auto-generated />
		#nullable enable

		namespace TestPlugin;

		internal partial class PluginLuaModule : global::CheatEngine.Client.Lua.IDescribedLuaModule, global::CheatEngine.Client.Lua.IOwnershipAwareLuaModule
		{
			/// <summary>Initializes a Lua module instance for activation-scoped dependency injection.</summary>
			public PluginLuaModule()
			{
			}

			private static readonly global::CheatEngine.Client.Lua.LuaModuleDescriptor s_descriptor =
				new global::CheatEngine.Client.Lua.LuaModuleDescriptor(
					"plugin",
					global::System.Collections.Immutable.ImmutableArray.Create(new global::CheatEngine.Client.Lua.LuaExportDescriptor("status"), new global::CheatEngine.Client.Lua.LuaExportDescriptor("ping")));

			/// <inheritdoc />
			public global::CheatEngine.Client.Lua.LuaModuleDescriptor Descriptor => s_descriptor;

			private const string __CheatEngineLuaModuleName = "plugin";

			private static readonly string[] __CheatEngineLuaExportNames = new string[] { "status", "ping" };

			// One pin per export, in export order, while a registration is owned; null otherwise.
			private object[]? __CheatEngineLuaOwnedExports;

			private global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome? __CheatEngineLuaLastReleaseOutcome;

			/// <inheritdoc />
			public global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome? LastReleaseOutcome =>
				global::System.Threading.Volatile.Read(ref __CheatEngineLuaLastReleaseOutcome);

			/// <inheritdoc />
			public void Register()
			{
				using global::CheatEngine.SDK.Lua.Runtime.LuaRuntimeOperation operation =
					global::CheatEngine.SDK.Lua.Runtime.LuaRuntime.AcquireOperation();
				__CheatEngineLuaSdkPort port = new __CheatEngineLuaSdkPort(operation.State);
				__CheatEngineLuaRegisterCore<__CheatEngineLuaSdkPort, global::CheatEngine.SDK.Lua.References.LuaRef>(ref port);
			}

			/// <inheritdoc />
			public void Unregister()
			{
				if (__CheatEngineLuaOwnedExports is null)
				{
					return;
				}

				using global::CheatEngine.SDK.Lua.Runtime.LuaRuntimeOperation operation =
					global::CheatEngine.SDK.Lua.Runtime.LuaRuntime.AcquireOperation();
				__CheatEngineLuaSdkPort port = new __CheatEngineLuaSdkPort(operation.State);
				__CheatEngineLuaUnregisterCore<__CheatEngineLuaSdkPort, global::CheatEngine.SDK.Lua.References.LuaRef>(ref port);
			}

			private void __CheatEngineLuaRegisterCore<TPort, TToken>(ref TPort port)
				where TPort : __CheatEngineLuaIGlobalPort<TToken>
				where TToken : class
			{
				object[]? previous = __CheatEngineLuaOwnedExports;
				if (previous is not null)
				{
					for (int export = 0; export < previous.Length; export++)
					{
						if (port.IsCurrent((TToken) previous[export]))
						{
							throw new global::System.InvalidOperationException("Client Lua module '" + __CheatEngineLuaModuleName + "' is already registered in the current Lua state.");
						}
					}

					// The previous registration belongs to an earlier Lua state or attachment: releasing its pins cannot reach
					// the current state, it only marks them released.
					__CheatEngineLuaOwnedExports = null;
					for (int export = 0; export < previous.Length; export++)
					{
						_ = port.Release((TToken) previous[export]);
					}
				}

				int count = __CheatEngineLuaExportNames.Length;
				for (int export = 0; export < count; export++)
				{
					global::System.Exception? probeFailure = port.ProbeVacant(export, out bool vacant);
					if (probeFailure is not null)
					{
						throw probeFailure;
					}

					if (!vacant)
					{
						throw new global::System.InvalidOperationException("Lua global '" + __CheatEngineLuaExportNames[export] + "' is already defined and cannot be replaced by Client module '" + __CheatEngineLuaModuleName + "'.");
					}
				}

				TToken?[] captured = new TToken?[count];
				global::System.Exception? primary = port.Publish();
				for (int export = 0; primary is null && export < count; export++)
				{
					primary = port.Capture(export, out TToken? token);
					captured[export] = token;
					if (primary is null && token is null)
					{
						primary = new global::System.InvalidOperationException("Lua global '" + __CheatEngineLuaExportNames[export] + "' could not be confirmed after Client module '" + __CheatEngineLuaModuleName + "' registered it.");
					}
				}

				if (primary is not null)
				{
					throw __CheatEngineLuaRollback<TPort, TToken>(ref port, captured, primary);
				}

				object[] owned = new object[count];
				for (int export = 0; export < count; export++)
				{
					owned[export] = captured[export]!;
				}

				__CheatEngineLuaOwnedExports = owned;
			}

			private void __CheatEngineLuaUnregisterCore<TPort, TToken>(ref TPort port)
				where TPort : __CheatEngineLuaIGlobalPort<TToken>
				where TToken : class
			{
				object[]? owned = __CheatEngineLuaOwnedExports;
				if (owned is null)
				{
					return;
				}

				// Ownership is consumed before the first Lua call: a release is attempted once and never retried.
				__CheatEngineLuaOwnedExports = null;
				bool stale = false;
				for (int export = 0; export < owned.Length; export++)
				{
					stale |= !port.IsCurrent((TToken) owned[export]);
				}

				global::CheatEngine.Client.Lua.LuaExportReleaseOutcome[] exports = new global::CheatEngine.Client.Lua.LuaExportReleaseOutcome[owned.Length];
				global::System.Collections.Generic.List<global::System.Exception>? failures = null;
				for (int export = 0; export < owned.Length; export++)
				{
					TToken token = (TToken) owned[export];
					global::CheatEngine.Client.Lua.LuaExportReleaseStatus status;
					if (stale)
					{
						status = global::CheatEngine.Client.Lua.LuaExportReleaseStatus.NotAttempted;
						__CheatEngineLuaAddFailure(ref failures, port.Release(token));
					}
					else
					{
						status = __CheatEngineLuaReleaseExport<TPort, TToken>(ref port, export, token, ref failures);
					}

					exports[export] = new global::CheatEngine.Client.Lua.LuaExportReleaseOutcome(__CheatEngineLuaExportNames[export], status);
				}

				global::System.Threading.Volatile.Write(ref __CheatEngineLuaLastReleaseOutcome,
					new global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome(__CheatEngineLuaModuleName, global::System.Collections.Immutable.ImmutableArray.Create(exports)));
				if (failures is null)
				{
					return;
				}

				if (failures.Count == 1)
				{
					throw failures[0];
				}

				throw new global::System.AggregateException("Client Lua module '" + __CheatEngineLuaModuleName + "' could not release every export.", failures);
			}

			private static global::System.Exception __CheatEngineLuaRollback<TPort, TToken>(ref TPort port, TToken?[] captured, global::System.Exception primary)
				where TPort : __CheatEngineLuaIGlobalPort<TToken>
				where TToken : class
			{
				// Captured exports are released ownership-aware. The preflight proved the others were nil inside this admitted
				// operation, so a non-nil value there was published by this registration (a _G metamethod that publishes under
				// the module's names during registration is unsupported).
				global::System.Collections.Generic.List<global::System.Exception>? secondary = null;
				for (int export = 0; export < captured.Length; export++)
				{
					TToken? token = captured[export];
					if (token is not null)
					{
						_ = __CheatEngineLuaReleaseExport<TPort, TToken>(ref port, export, token, ref secondary);
						continue;
					}

					global::System.Exception? failure = port.ProbeVacant(export, out bool vacant);
					if (failure is null && !vacant)
					{
						failure = port.Clear(export);
					}

					__CheatEngineLuaAddFailure(ref secondary, failure);
				}

				if (secondary is null)
				{
					return primary;
				}

				global::System.Text.StringBuilder message = new global::System.Text.StringBuilder(primary.Message);
				message.Append(" The rollback also failed:");
				foreach (global::System.Exception failure in secondary)
				{
					message.Append(' ').Append(failure.Message);
				}

				secondary.Insert(0, primary);
				global::System.AggregateException inner = new global::System.AggregateException(secondary);
				return primary is global::CheatEngine.SDK.Lua.Calls.LuaException
					? new global::CheatEngine.SDK.Lua.Calls.LuaException(message.ToString(), inner)
					: new global::System.InvalidOperationException(message.ToString(), inner);
			}

			private static global::CheatEngine.Client.Lua.LuaExportReleaseStatus __CheatEngineLuaReleaseExport<TPort, TToken>(ref TPort port, int export, TToken token,
				ref global::System.Collections.Generic.List<global::System.Exception>? failures)
				where TPort : __CheatEngineLuaIGlobalPort<TToken>
				where TToken : class
			{
				global::CheatEngine.Client.Lua.LuaExportReleaseStatus status;
				global::System.Exception? failure;
				switch (port.Observe(export, token, out global::System.Exception? readFailure))
				{
					case __CheatEngineLuaOwnership.Owned:
						failure = port.Clear(export);
						status = failure is null ? global::CheatEngine.Client.Lua.LuaExportReleaseStatus.Removed : global::CheatEngine.Client.Lua.LuaExportReleaseStatus.Failed;
						break;
					case __CheatEngineLuaOwnership.Replaced:
						failure = null;
						status = global::CheatEngine.Client.Lua.LuaExportReleaseStatus.Replaced;
						break;
					case __CheatEngineLuaOwnership.Absent:
						failure = null;
						status = global::CheatEngine.Client.Lua.LuaExportReleaseStatus.Absent;
						break;
					case __CheatEngineLuaOwnership.OwnershipUnresolvable:
						failure = new global::System.InvalidOperationException("Client Lua module '" + __CheatEngineLuaModuleName + "' could not resolve the ownership reference of Lua global '" + __CheatEngineLuaExportNames[export] + "'; the global was left untouched.");
						status = global::CheatEngine.Client.Lua.LuaExportReleaseStatus.Failed;
						break;
					default:
						failure = readFailure ?? new global::System.InvalidOperationException("Client Lua module '" + __CheatEngineLuaModuleName + "' could not read Lua global '" + __CheatEngineLuaExportNames[export] + "'.");
						status = global::CheatEngine.Client.Lua.LuaExportReleaseStatus.Failed;
						break;
				}

				__CheatEngineLuaAddFailure(ref failures, failure);
				// A pin that cannot be released is a secondary failure; it does not change what happened to the global.
				__CheatEngineLuaAddFailure(ref failures, port.Release(token));
				return status;
			}

			private static void __CheatEngineLuaAddFailure(ref global::System.Collections.Generic.List<global::System.Exception>? failures, global::System.Exception? failure)
			{
				if (failure is not null)
				{
					(failures ??= new global::System.Collections.Generic.List<global::System.Exception>()).Add(failure);
				}
			}

			private enum __CheatEngineLuaOwnership
			{
				ReadFailed,
				Absent,
				Owned,
				Replaced,
				OwnershipUnresolvable
			}

			// Every observation the ownership algorithm needs; each member restores the Lua stack it used.
			private interface __CheatEngineLuaIGlobalPort<TToken>
				where TToken : class
			{
				global::System.Exception? ProbeVacant(int export, out bool vacant);

				global::System.Exception? Publish();

				global::System.Exception? Capture(int export, out TToken? token);

				bool IsCurrent(TToken token);

				__CheatEngineLuaOwnership Observe(int export, TToken token, out global::System.Exception? failure);

				global::System.Exception? Clear(int export);

				global::System.Exception? Release(TToken token);
			}

			// ADR-01 registered exception (Q16 on CheatEngine.SDK 1.0.0): the only raw Lua access in generated Client code. Removal: SDK 2.0 registration leases (docs/migration/sdk-2.0.md).
			private readonly struct __CheatEngineLuaSdkPort : __CheatEngineLuaIGlobalPort<global::CheatEngine.SDK.Lua.References.LuaRef>
			{
				private readonly global::CheatEngine.SDK.Lua.State.LuaState _state;

				public __CheatEngineLuaSdkPort(global::CheatEngine.SDK.Lua.State.LuaState state)
				{
					_state = state;
				}

				public global::System.Exception? ProbeVacant(int export, out bool vacant)
				{
					vacant = false;
					int top = _state.Top;
					try
					{
						global::CheatEngine.SDK.Lua.Calls.LuaStatus status = _state.TryGetGlobal(ExportName(export));
						if (!status.IsOk)
						{
							return new global::CheatEngine.SDK.Lua.Calls.LuaException(global::CheatEngine.SDK.Lua.Calls.LuaError.FromStack(_state, status));
						}

						vacant = _state.IsNil(-1);
						return null;
					}
					finally
					{
						_state.SetTop(top);
					}
				}

				public global::System.Exception? Publish()
				{
					int top = _state.Top;
					try
					{
						global::CheatEngine.SDK.Lua.Calls.LuaStatus status = global::TestPlugin.PluginLuaBindings.RegisterLuaFunctions(_state);
						return status.IsOk ? null : new global::CheatEngine.SDK.Lua.Calls.LuaException(global::CheatEngine.SDK.Lua.Calls.LuaError.FromStack(_state, status));
					}
					finally
					{
						_state.SetTop(top);
					}
				}

				public global::System.Exception? Capture(int export, out global::CheatEngine.SDK.Lua.References.LuaRef? token)
				{
					token = null;
					int top = _state.Top;
					try
					{
						global::CheatEngine.SDK.Lua.Calls.LuaStatus status = _state.TryGetGlobal(ExportName(export));
						if (!status.IsOk)
						{
							return new global::CheatEngine.SDK.Lua.Calls.LuaException(global::CheatEngine.SDK.Lua.Calls.LuaError.FromStack(_state, status));
						}

						if (_state.IsNil(-1))
						{
							return null;
						}

						token = _state.CreateRef();
						return null;
					}
					catch (global::CheatEngine.SDK.Lua.Calls.LuaException exception)
					{
						return exception;
					}
					finally
					{
						_state.SetTop(top);
					}
				}

				public bool IsCurrent(global::CheatEngine.SDK.Lua.References.LuaRef token)
				{
					return token.IsCurrent;
				}

				public __CheatEngineLuaOwnership Observe(int export, global::CheatEngine.SDK.Lua.References.LuaRef token, out global::System.Exception? failure)
				{
					failure = null;
					int top = _state.Top;
					try
					{
						global::CheatEngine.SDK.Lua.Calls.LuaStatus status = _state.TryGetGlobal(ExportName(export));
						if (!status.IsOk)
						{
							failure = new global::CheatEngine.SDK.Lua.Calls.LuaException(global::CheatEngine.SDK.Lua.Calls.LuaError.FromStack(_state, status));
							return __CheatEngineLuaOwnership.ReadFailed;
						}

						if (_state.IsNil(-1))
						{
							return __CheatEngineLuaOwnership.Absent;
						}

						if (!_state.TryPushRef(token))
						{
							return __CheatEngineLuaOwnership.OwnershipUnresolvable;
						}

						return _state.RawEquals(-2, -1) ? __CheatEngineLuaOwnership.Owned : __CheatEngineLuaOwnership.Replaced;
					}
					finally
					{
						_state.SetTop(top);
					}
				}

				public global::System.Exception? Clear(int export)
				{
					int top = _state.Top;
					try
					{
						_state.PushNil();
						global::CheatEngine.SDK.Lua.Calls.LuaStatus status = _state.TrySetGlobal(ExportName(export));
						return status.IsOk ? null : new global::CheatEngine.SDK.Lua.Calls.LuaException(global::CheatEngine.SDK.Lua.Calls.LuaError.FromStack(_state, status));
					}
					finally
					{
						_state.SetTop(top);
					}
				}

				public global::System.Exception? Release(global::CheatEngine.SDK.Lua.References.LuaRef token)
				{
					int top = _state.Top;
					try
					{
						token.Release(_state);
						return null;
					}
					catch (global::CheatEngine.SDK.Lua.Calls.LuaException exception)
					{
						return exception;
					}
					finally
					{
						_state.SetTop(top);
					}
				}

				private static global::System.ReadOnlySpan<byte> ExportName(int export)
				{
					switch (export)
					{
						case 0:
							return "status"u8;
						case 1:
							return "ping"u8;
						default:
							throw new global::System.ArgumentOutOfRangeException(nameof(export));
					}
				}
			}
		}
		""";

	[Fact]
	public void ModuleAdapterSnapshotMatchesTheOwnershipAwareContract()
	{
		GeneratorRun run = GeneratorRun.Execute(ModuleSource);

		Assert.Empty(run.Diagnostics);
		Assert.Equal(Normalize(OwnershipAwareModuleGolden) + "\n",
			Normalize(run.GeneratedText("PluginLuaModule.CheatEngineLuaModule.g.cs")));
	}

	private static string Normalize(string text)
	{
		return text.Replace("\r\n", "\n", StringComparison.Ordinal);
	}
}
