using System.Runtime.Versioning;

using CheatEngine.Client.Tests.Infrastructure;

namespace CheatEngine.Client.Tests.LiveQualification;

/// <summary>
///     The autorun driver, as reviewed text: every change to the Lua that runs inside Cheat Engine shows up here first. It
///     only calls functions the harness declares, never attempts an unproven settings toggle (it prompts the operator and
///     waits for the toggle's effect), and quotes every value.
/// </summary>
[SupportedOSPlatform("windows")]
public sealed class LuaDriverScriptTests
{
	private const string TranscriptPath = @"C:\runs\20260924T101530Z-a1b2\sessions\S0\transcript.txt";
	private const string PluginPath = @"C:\runs\20260924T101530Z-a1b2\plugins\harness\CheatEngine.Client.LivePlugin.Qualification.dll";

	/// <summary>The reviewed S0 driver.</summary>
	private const string SpikeDriver = """
		-- Generated by CheatEngine.Client.Tests (LiveQualification) for session S0. Never committed: it
		-- lives in the run's sandboxed Cheat Engine only. One step per timer tick on the main thread, each under pcall;
		-- every step appends "R<TAB>step<TAB>ok|error|notexecuted<TAB>%q" to the transcript and flushes it.
		local transcript = assert(io.open("C:\\runs\\20260924T101530Z-a1b2\\sessions\\S0\\transcript.txt", "wb"))

		local function record(step, status, value)
		  transcript:write(string.format("R\t%s\t%s\t%q\n", step, status, tostring(value)))
		  transcript:flush()
		end

		local steps = {
		  { name = "main-form", kind = "poll", attempts = 240, run = function()
		    if getMainForm() == nil then return nil end
		    return "ready"
		  end },
		  { name = "open-process", kind = "once", run = function()
		    return openProcess(4242)
		  end },
		  { name = "opened-process", kind = "poll", attempts = 40, run = function()
		    if getOpenedProcessID() ~= 4242 then return nil end
		    return getOpenedProcessID()
		  end },
		  { name = "load-plugin", kind = "once", run = function()
		    return loadPlugin("C:\\runs\\20260924T101530Z-a1b2\\plugins\\harness\\CheatEngine.Client.LivePlugin.Qualification.dll")
		  end },
		  { name = "harness-ready", kind = "poll", attempts = 40, run = function()
		    if type(_G["cheatengine_client_qualification_status"]) ~= "function" then return nil end
		    return "ready"
		  end },
		  { name = "status", kind = "once", run = function()
		    local harness = _G["cheatengine_client_qualification_status"]
		    if type(harness) ~= "function" then error("the harness does not define " .. "cheatengine_client_qualification_status") end
		    return harness()
		  end },
		  { name = "runtime", kind = "once", run = function()
		    local harness = _G["cheatengine_client_qualification_runtime"]
		    if type(harness) ~= "function" then error("the harness does not define " .. "cheatengine_client_qualification_runtime") end
		    return harness()
		  end },
		  { name = "capabilities", kind = "once", run = function()
		    local harness = _G["cheatengine_client_qualification_capabilities"]
		    if type(harness) ~= "function" then error("the harness does not define " .. "cheatengine_client_qualification_capabilities") end
		    return harness(1)
		  end },
		  { name = "settings-probe", kind = "once", run = function()
		    local form = getSettingsForm()
		    if form == nil then return "no settings form" end
		    local found = {}
		    for index = 0, form.ComponentCount - 1 do
		      local component = form.Component[index]
		      if string.find(component.ClassName, "CheckListBox", 1, true) ~= nil then
		        found[#found + 1] = component.Name .. ":" .. component.ClassName .. ":" .. tostring(component.Items.Count)
		      end
		    end
		    return table.concat(found, ";")
		  end },
		  { name = "toggle-disable", kind = "operator", attempts = 360, prompt = "Operator: in Edit > Settings > Plugins, untick 'CheatEngine.Client Qualification Plugin' and press OK. The driver continues once the plugin's functions are gone.", run = function()
		    if type(_G["cheatengine_client_qualification_status"]) == "function" then return nil end
		    return "disabled"
		  end },
		  { name = "toggle-enable", kind = "operator", attempts = 360, prompt = "Operator: in Edit > Settings > Plugins, tick 'CheatEngine.Client Qualification Plugin' and press OK. The driver continues once the plugin's functions are back.", run = function()
		    if type(_G["cheatengine_client_qualification_status"]) ~= "function" then return nil end
		    return "enabled"
		  end },
		  { name = "clear-address-list", kind = "once", run = function()
		    getAddressList().clear()
		    return getAddressList().Count
		  end },
		}

		local index = 1
		local attempts = 0
		local finished = false

		-- The operator window: it does not block Cheat Engine, so the operator can open Settings > Plugins.
		local prompt = nil
		local answer = nil

		local function closePrompt()
		  local form = prompt
		  prompt = nil
		  if form ~= nil then
		    pcall(function() form.destroy() end)
		  end
		  answer = nil
		end

		local function showPrompt(step)
		  local form = createForm(false)
		  prompt = form
		  form.Caption = "CheatEngine.Client qualification: operator step " .. step.name
		  form.setSize(560, 180)
		  pcall(function() form.FormStyle = "fsStayOnTop" end)
		  local text = createMemo(form)
		  text.setPosition(12, 12)
		  text.setSize(536, 96)
		  text.WordWrap = true
		  pcall(function() text.ReadOnly = true end)
		  text.append(step.prompt)
		  local skip = createButton(form)
		  skip.Caption = "Skip"
		  skip.setPosition(460, 124)
		  skip.OnClick = function() answer = "skip" end
		  if step.run == nil then
		    local done = createButton(form)
		    done.Caption = "Done"
		    done.setPosition(372, 124)
		    done.OnClick = function() answer = "done" end
		  end
		  form.OnClose = function()
		    -- Closing the window skips the step; a window the driver destroys is no longer the prompt.
		    if prompt == form and answer == nil then answer = "skip" end
		    return 1 -- caHide
		  end
		  form.centerScreen()
		  form.show()
		end

		local function operatorStep(step)
		  local ok, value = true, nil
		  if step.run ~= nil then
		    ok, value = pcall(step.run)
		  elseif answer == "done" then
		    value = "confirmed by the operator"
		  end
		  if not ok then
		    record(step.name, "error", value)
		  elseif value ~= nil then
		    record(step.name, "ok", value)
		  elseif answer == "skip" then
		    record(step.name, "notexecuted", "skipped by the operator: " .. step.prompt)
		  elseif attempts + 1 >= step.attempts then
		    record(step.name, "notexecuted", "no operator action within 90 seconds: " .. step.prompt)
		  else
		    if prompt == nil then
		      local shown, failure = pcall(showPrompt, step)
		      if not shown then
		        closePrompt()
		        record(step.name, "error", failure)
		        return true
		      end
		    end
		    attempts = attempts + 1
		    return false
		  end
		  closePrompt()
		  return true
		end

		local function advance()
		  local step = steps[index]
		  if step == nil then
		    finished = true
		    pcall(function()
		      transcript:write("DONE\n")
		      transcript:flush()
		      transcript:close()
		    end)
		    closeCE()
		    return
		  end
		  if step.kind == "operator" then
		    if not operatorStep(step) then return end
		    index = index + 1
		    attempts = 0
		    return
		  end
		  local ok, value = pcall(step.run)
		  if not ok then
		    record(step.name, "error", value)
		  elseif value ~= nil or step.kind == "once" then
		    record(step.name, "ok", value)
		  else
		    attempts = attempts + 1
		    if attempts < step.attempts then return end
		    record(step.name, "error", "no result after " .. attempts .. " attempts")
		  end
		  index = index + 1
		  attempts = 0
		end

		local driver = createTimer(nil, false)
		driver.Interval = 250
		driver.OnTimer = function(sender)
		  sender.Enabled = false
		  local ok, failure = pcall(advance)
		  if not ok then
		    -- The driver itself failed: still clear the address list, then write DONE and close.
		    pcall(closePrompt)
		    pcall(record, "driver", "error", failure)
		    index = index < #steps and #steps or #steps + 1
		  end
		  if not finished then sender.Enabled = true end
		end
		driver.Enabled = true
		""";

	[Fact]
	public void TheSpikeDriverIsTheReviewedText()
	{
		string rendered = LuaDriverScript.Render(LuaDriverScript.SpikePlan(TranscriptPath, 4242, PluginPath, LiveSandboxSession.HarnessDisplayName));

		// The driver is written with LF line endings and ends with one.
		Assert.Equal(SpikeDriver.ReplaceLineEndings("\n") + "\n", rendered);
	}

	[Fact]
	public void LiteralsEscapeQuotesBackslashesControlAndNonAsciiBytes()
	{
		Assert.Equal("\"a\\\"b\\\\c\\010d\\195\\169\"", LuaLiteral.String("a\"b\\c\nd\u00e9"));
		Assert.Equal("\"\"", LuaLiteral.String(string.Empty));
		Assert.Equal("-12", LuaLiteral.Integer(-12));
	}

	[Fact]
	public void AnUnprovenSettingsToggleIsNeverAttempted()
	{
		LuaDriverPlan plan = LuaDriverScript.SpikePlan(TranscriptPath, 4242, PluginPath, LiveSandboxSession.HarnessDisplayName);

		string rendered = LuaDriverScript.Render(plan);

		Assert.Throws<NotSupportedException>(() => LuaDriverScript.Render(plan with { SettingsToggleProven = true }));
		Assert.Contains("name = \"toggle-disable\", kind = \"operator\"", rendered, StringComparison.Ordinal);
		Assert.Contains("name = \"toggle-enable\", kind = \"operator\"", rendered, StringComparison.Ordinal);
		Assert.DoesNotContain("getSettingsForm", rendered[rendered.IndexOf("toggle-disable", StringComparison.Ordinal)..],
			StringComparison.Ordinal);
		Assert.DoesNotContain("Checked", rendered, StringComparison.Ordinal);
		Assert.DoesNotContain("ModalResult", rendered, StringComparison.Ordinal);
	}

	[Theory]
	[InlineData("bad step", "status")]
	[InlineData("status", "Bad-Name")]
	[InlineData("", "status")]
	[InlineData("status\t", "status")]
	public void InvalidStepOrFunctionNamesAreRefused(string step, string function)
	{
		LuaDriverPlan plan = LuaDriverScript.SpikePlan(TranscriptPath, 4242, PluginPath, LiveSandboxSession.HarnessDisplayName) with
		{
			Calls = [new LuaHarnessCall(step, function, [])]
		};

		Assert.Throws<ArgumentException>(() => LuaDriverScript.Render(plan));
	}

	[Fact]
	public void TheDriverCallsOnlyFunctionsTheHarnessDeclares()
	{
		string functions = File.ReadAllText(RepositoryLayout.Combine(
			"tests/CheatEngine.Client.LivePlugin.Qualification/QualificationLuaFunctions.cs"));
		string plugin = File.ReadAllText(RepositoryLayout.Combine("tests/CheatEngine.Client.LivePlugin.Qualification/QualificationPlugin.cs"));
		LuaDriverPlan plan = LuaDriverScript.SpikePlan(TranscriptPath, 4242, PluginPath, LiveSandboxSession.HarnessDisplayName);

		Assert.Contains($"DisplayName = \"{LiveSandboxSession.HarnessDisplayName}\";", plugin, StringComparison.Ordinal);
		Assert.Contains($"[LuaFunction(\"{LuaDriverScript.HarnessFunctionPrefix}status\")]", functions, StringComparison.Ordinal);
		Assert.All(plan.Calls, call => Assert.Contains($"[LuaFunction(\"{LuaDriverScript.HarnessFunctionPrefix}{call.Function}\")]",
			functions, StringComparison.Ordinal));
		Assert.Contains("[CheatEnginePlugin(DisplayName)]", plugin, StringComparison.Ordinal);
	}
}
