namespace CheatEngine.Client.SourceGenerators.Lua;

/// <summary>
///     Emits, once per compilation that declares a valid <c>[CheatEngineLuaModule]</c>, the internal registrar that every
///     generated module of that assembly calls, and the CheatEngine.SDK adapter behind it.
/// </summary>
/// <remarks>
///     <para>
///         The registrar (<see cref="RegistrarSource" />) takes every decision: when to admit a Lua operation and end it,
///         which lease to release (an earlier registration of the module, the residual lease a failed publication left),
///         when to consume the module's lease, how to map the admission, the registration result and the release that
///         CheatEngine.SDK reports to the Client vocabulary, and which classified refusal to throw. It makes no SDK call.
///     </para>
///     <para>
///         The adapter (<see cref="AdapterSource" />) is the only generated code that calls CheatEngine.SDK, and it takes no
///         decision: each of its members is one SDK call (<c>LuaRuntime.TryAcquireOperationWithOutcome</c>, the end of
///         the admitted operation, the module's <c>TryRegisterLuaFunctions</c> delegate, and
///         <c>LuaRegistrationLease.ReleaseWithOutcome</c> with or without a state) whose result it copies into Client-owned
///         values. It is emitted as its own file so that a test compilation can replace it with a managed double of the
///         SDK registration set (<c>LuaRegistrationLease</c> has no public constructor), while the registrar and the
///         modules run unchanged. The SDK members it may use are the exact allowlist of
///         <c>GeneratedLuaSurfaceRatchetTests</c>.
///     </para>
/// </remarks>
internal static class RegistrarEmitter
{
	/// <summary>The namespace of the generated registrar and adapter.</summary>
	internal const string Namespace = "CheatEngine.Client.Lua.Generated";

	/// <summary>The simple name of the generated registrar that modules call.</summary>
	internal const string RegistrarType = "CheatEngineLuaModuleRegistrar";

	/// <summary>The simple name of the generated CheatEngine.SDK adapter.</summary>
	internal const string AdapterType = "CheatEngineLuaRegistrationAdapter";

	/// <summary>The hint name of the registrar file.</summary>
	internal const string RegistrarHintName = Namespace + "." + RegistrarType + ".g.cs";

	/// <summary>The hint name of the adapter file.</summary>
	internal const string AdapterHintName = Namespace + "." + AdapterType + ".g.cs";

	/// <summary>The registrar and the Client-owned values the adapter fills; constant text.</summary>
	internal const string RegistrarSource =
		"""
		// <auto-generated />
		#nullable enable

		namespace CheatEngine.Client.Lua.Generated;

		/// <summary>
		///     Registers and releases this assembly's <c>[CheatEngineLuaModule]</c> modules through CheatEngine.SDK Lua
		///     registration leases and reports what CheatEngine.SDK observed in the Client vocabulary. It runs inside a
		///     module's <c>Register</c> and <c>Unregister</c>, on Cheat Engine's main thread, and takes every decision; each
		///     CheatEngine.SDK call goes through one member of <see cref="CheatEngineLuaRegistrationAdapter" />.
		/// </summary>
		internal static class CheatEngineLuaModuleRegistrar
		{
			private const string RegisterOperation = "Lua.RegisterModule";

			/// <summary>Publishes a module's globals and keeps the registration lease in <paramref name="registration" />.</summary>
			/// <exception cref="global::CheatEngine.Client.Results.CheatEngineOperationException">
			///     CheatEngine.SDK refused the Lua admission, a global is already defined, or a protected operation failed.
			/// </exception>
			internal static void Register(global::CheatEngine.Client.Lua.LuaModuleDescriptor descriptor, ref object? registration,
				global::System.Func<global::CheatEngine.SDK.Lua.State.LuaState, global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResult> publish)
			{
				global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus admission = CheatEngineLuaRegistrationAdapter.TryAdmit(
					out global::CheatEngine.SDK.Lua.Runtime.LuaRuntimeOperation operation,
					out global::CheatEngine.SDK.Lua.State.LuaState state);
				if (admission != global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.Admitted)
				{
					// Nothing ran: a registration the module already owned is still owned.
					throw new global::CheatEngine.Client.Results.CheatEngineOperationException(Refused(admission));
				}

				CheatEngineLuaPublication publication;
				CheatEngineLuaRelease previous = default;
				CheatEngineLuaRelease residual = default;
				try
				{
					object? owned = registration;
					if (owned is not null)
					{
						// Released inside this admitted operation before the same globals are published again: a current
						// lease is released ownership-aware, a lease of an earlier attachment or Lua state is only forgotten.
						registration = null;
						previous = CheatEngineLuaRegistrationAdapter.Release(owned, state);
						if (!LeftNothingOwned(previous.Kind))
						{
							// A global of the earlier registration may still hold the module's own function: publishing
							// would report it as a third party's. Nothing is published, and the release is the failure.
							throw new global::CheatEngine.Client.Results.CheatEngineOperationException(
								NotReleased(descriptor.Name, previous));
						}
					}

					publication = CheatEngineLuaRegistrationAdapter.Publish(publish, state);
					if (publication.Lease is not null &&
						publication.Kind != global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.Succeeded)
					{
						// The SDK compensation left a residual owner: release it once more inside this admitted operation.
						residual = CheatEngineLuaRegistrationAdapter.Release(publication.Lease, state);
					}
				}
				finally
				{
					CheatEngineLuaRegistrationAdapter.EndOperation(ref operation);
				}

				if (publication.Kind == global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.Succeeded &&
					publication.Lease is not null)
				{
					registration = publication.Lease;
					return;
				}

				throw new global::CheatEngine.Client.Results.CheatEngineOperationException(
					Failed(descriptor.Name, publication, previous, residual));
			}

			/// <summary>Releases the registration lease in <paramref name="registration" /> and reports what happened.</summary>
			internal static global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome Unregister(
				global::CheatEngine.Client.Lua.LuaModuleDescriptor descriptor, ref object? registration)
			{
				object? lease = registration;
				if (lease is null)
				{
					return global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome.AlreadyReleased(descriptor.Name);
				}

				global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus admission = CheatEngineLuaRegistrationAdapter.TryAdmit(
					out global::CheatEngine.SDK.Lua.Runtime.LuaRuntimeOperation operation,
					out global::CheatEngine.SDK.Lua.State.LuaState state);
				CheatEngineLuaRelease release;
				switch (admission)
				{
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.Admitted:
						registration = null;
						try
						{
							release = CheatEngineLuaRegistrationAdapter.Release(lease, state);
						}
						finally
						{
							CheatEngineLuaRegistrationAdapter.EndOperation(ref operation);
						}

						return ToOutcome(descriptor, release);
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.Detached:
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.ExternalStateReset:
						// The Lua universe that holds the registration is no longer this attachment's: the lease is consumed
						// without any Lua operation, and CheatEngine.SDK reports it stale.
						registration = null;
						return ToOutcome(descriptor, CheatEngineLuaRegistrationAdapter.ReleaseStale(lease));
					default:
						// Nothing ran: the registration stays owned for a later release or the activation cleanup.
						return global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome.CleanupUnavailable(descriptor.Name,
							descriptor.Exports.Length);
				}
			}

			/// <summary>
			///     Maps the kind CheatEngine.SDK reports for the release of a lease the registrar consumed to the Client lease
			///     vocabulary; total and fail-closed.
			/// </summary>
			/// <remarks>
			///     The lease is consumed before the release runs, so a later attempt could only report
			///     <c>AlreadyReleased</c>: a kind outside the documented release shape is never retryable. It is
			///     <c>CleanupUnconfirmed</c>, which requires manual recovery and which the activation cleanup reports.
			/// </remarks>
			internal static global::CheatEngine.Client.Results.LeaseReleaseKind MapReleaseKind(
				global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind kind)
			{
				switch (kind)
				{
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.Released:
						return global::CheatEngine.Client.Results.LeaseReleaseKind.Released;
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.PartiallyReleased:
						return global::CheatEngine.Client.Results.LeaseReleaseKind.PartiallyReleased;
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.Stale:
						// An earlier attachment or Lua state: nothing was written, and its globals may remain.
						return global::CheatEngine.Client.Results.LeaseReleaseKind.RefusedRuntimeChanged;
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.AlreadyReleased:
						return global::CheatEngine.Client.Results.LeaseReleaseKind.AlreadyReleased;
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.NotAttempted:
						// The SDK's value before any release, never the result of one: the lease is consumed all the same.
					default:
						// A kind a later CheatEngine.SDK adds: the release began on a consumed lease and is not confirmed.
						return global::CheatEngine.Client.Results.LeaseReleaseKind.CleanupUnconfirmed;
				}
			}

			/// <summary>Classifies a Lua admission that CheatEngine.SDK refused; total and fail-closed.</summary>
			internal static global::CheatEngine.Client.Results.CheatEngineFailureKind MapAdmission(
				global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus status)
			{
				switch (status)
				{
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.Detached:
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.TransitionInProgress:
						return global::CheatEngine.Client.Results.CheatEngineFailureKind.ActivationExpired;
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.ExternalStateReset:
						return global::CheatEngine.Client.Results.CheatEngineFailureKind.RuntimeChanged;
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.ThreadNotAdmitted:
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.NoStateForThread:
					case global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.Unknown:
					default:
						return global::CheatEngine.Client.Results.CheatEngineFailureKind.InvalidState;
				}
			}

			/// <summary>Classifies a registration result that is not a success; total and fail-closed.</summary>
			internal static global::CheatEngine.Client.Results.CheatEngineFailureKind MapResultKind(
				global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind kind)
			{
				switch (kind)
				{
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.Collision:
						return global::CheatEngine.Client.Results.CheatEngineFailureKind.OperationRejected;
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.PreflightFailed:
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.PublicationFailed:
						return global::CheatEngine.Client.Results.CheatEngineFailureKind.LuaError;
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.Unspecified:
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.Succeeded:
					default:
						// No result, or a success without a registration lease: outside the documented result shape.
						return global::CheatEngine.Client.Results.CheatEngineFailureKind.InvalidHostResult;
				}
			}

			/// <summary>Copies the CheatEngine.SDK release of a consumed lease into the Client outcome of one module.</summary>
			internal static global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome ToOutcome(
				global::CheatEngine.Client.Lua.LuaModuleDescriptor descriptor, CheatEngineLuaRelease release)
			{
				global::CheatEngine.Client.Results.LeaseReleaseKind kind = MapReleaseKind(release.Kind);
				string[] failed = release.FailedExports ?? global::System.Array.Empty<string>();
				if (kind != global::CheatEngine.Client.Results.LeaseReleaseKind.PartiallyReleased)
				{
					failed = global::System.Array.Empty<string>();
				}
				else if (failed.Length == 0)
				{
					// A partial release that names no failed global is outside the documented result shape.
					kind = global::CheatEngine.Client.Results.LeaseReleaseKind.CleanupUnconfirmed;
				}

				int removed = global::System.Math.Max(release.RemovedCount, 0);
				int restored = global::System.Math.Max(release.RestoredCount, 0);
				int replaced = global::System.Math.Max(release.ReplacementCount, 0);
				int remaining = global::System.Math.Max(release.RemainingCount, failed.Length);
				if (kind == global::CheatEngine.Client.Results.LeaseReleaseKind.CleanupUnconfirmed)
				{
					// Every global the release did not report as handled may remain.
					remaining = global::System.Math.Max(remaining, descriptor.Exports.Length - removed - restored - replaced);
				}

				return global::CheatEngine.Client.Lua.LuaModuleReleaseOutcome.Create(descriptor.Name, kind, removed, restored,
					replaced, remaining, global::System.Collections.Immutable.ImmutableArray.Create(failed));
			}

			private static global::CheatEngine.Client.Results.CheatEngineFailure Refused(
				global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus admission)
			{
				return new global::CheatEngine.Client.Results.CheatEngineFailure(MapAdmission(admission), RegisterOperation,
					"CheatEngine.SDK refused the Lua operation (" + admission.ToString() + "); nothing was registered.",
					null, global::CheatEngine.Client.Results.CheatEngineHostEffect.NotStarted);
			}

			// Whether the release of the registration a module already owned left nothing of it that a publication could meet.
			private static bool LeftNothingOwned(global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind kind)
			{
				switch (kind)
				{
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.Released:
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.AlreadyReleased:
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.Stale:
						return true;
					default:
						return false;
				}
			}

			private static global::CheatEngine.Client.Results.CheatEngineFailure NotReleased(string moduleName,
				CheatEngineLuaRelease previous)
			{
				return new global::CheatEngine.Client.Results.CheatEngineFailure(
					previous.Kind == global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.PartiallyReleased
						? global::CheatEngine.Client.Results.CheatEngineFailureKind.LuaError
						: global::CheatEngine.Client.Results.CheatEngineFailureKind.InvalidHostResult,
					RegisterOperation,
					"Client Lua module '" + moduleName + "' could not release its earlier registration before registering " +
					"again; nothing was published. " + Describe("The release", previous),
					null, global::CheatEngine.Client.Results.CheatEngineHostEffect.CleanupUnconfirmed);
			}

			private static global::CheatEngine.Client.Results.CheatEngineFailure Failed(string moduleName,
				CheatEngineLuaPublication publication, CheatEngineLuaRelease previous, CheatEngineLuaRelease residual)
			{
				string name = publication.FailedExport ?? "(unnamed)";
				string status = publication.FailedStatus ?? "(unknown)";
				global::CheatEngine.Client.Results.CheatEngineFailureKind kind = MapResultKind(publication.Kind);
				switch (publication.Kind)
				{
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.Collision:
						// After a stale earlier registration, the global may be the module's own function of an earlier
						// attachment: the message says what that release reported.
						return new global::CheatEngine.Client.Results.CheatEngineFailure(kind, RegisterOperation,
							"Lua global '" + name + "' is already defined and cannot be replaced by Client module '" +
							moduleName + "'." +
							(previous.Kind == global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.NotAttempted
								? string.Empty
								: " " + Describe("The release of the module's earlier registration", previous)),
							null, global::CheatEngine.Client.Results.CheatEngineHostEffect.NotApplied);
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.PreflightFailed:
						return new global::CheatEngine.Client.Results.CheatEngineFailure(kind, RegisterOperation,
							"Client Lua module '" + moduleName + "' could not read Lua global '" + name +
							"' before its registration (" + status + "); nothing was published.",
							null, global::CheatEngine.Client.Results.CheatEngineHostEffect.NotApplied);
					case global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind.PublicationFailed:
						return new global::CheatEngine.Client.Results.CheatEngineFailure(kind, RegisterOperation,
							"Client Lua module '" + moduleName + "' could not publish Lua global '" + name + "' (" + status +
							"). " + Describe("The rollback", publication.Rollback) +
							(residual.Kind == global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.NotAttempted
								? string.Empty
								: " " + Describe("The release of what the rollback left", residual)),
							null, IsCleanedUp(publication.Rollback, residual)
								? global::CheatEngine.Client.Results.CheatEngineHostEffect.NotApplied
								: global::CheatEngine.Client.Results.CheatEngineHostEffect.CleanupUnconfirmed);
					default:
						return new global::CheatEngine.Client.Results.CheatEngineFailure(kind, RegisterOperation,
							"Client Lua module '" + moduleName + "' received the registration result " +
							publication.Kind.ToString() + " without a registration lease from CheatEngine.SDK.",
							null, global::CheatEngine.Client.Results.CheatEngineHostEffect.Unknown);
				}
			}

			// Nothing the failed publication installed remains: the rollback, or the release of what it left, removed it all.
			private static bool IsCleanedUp(CheatEngineLuaRelease rollback, CheatEngineLuaRelease residual)
			{
				return residual.Kind == global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.NotAttempted
					? rollback.Kind == global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.Released
					: residual.Kind == global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind.Released;
			}

			private static string Describe(string step, CheatEngineLuaRelease release)
			{
				string[] failed = release.FailedExports ?? global::System.Array.Empty<string>();
				return step + " reported " + release.Kind.ToString() + " (removed " +
					   release.RemovedCount.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + ", replaced " +
					   release.ReplacementCount.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + ", remaining " +
					   release.RemainingCount.ToString(global::System.Globalization.CultureInfo.InvariantCulture) +
					   (failed.Length == 0 ? string.Empty : ", failed " + string.Join(", ", failed)) + ").";
			}
		}

		/// <summary>What CheatEngine.SDK reported for one release of a registration lease, copied without any Lua handle.</summary>
		internal readonly struct CheatEngineLuaRelease
		{
			internal readonly global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind Kind;
			internal readonly int RemovedCount;
			internal readonly int RestoredCount;
			internal readonly int ReplacementCount;
			internal readonly int RemainingCount;
			internal readonly string[]? FailedExports;

			internal CheatEngineLuaRelease(global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseKind kind,
				int removedCount, int restoredCount, int replacementCount, int remainingCount, string[] failedExports)
			{
				Kind = kind;
				RemovedCount = removedCount;
				RestoredCount = restoredCount;
				ReplacementCount = replacementCount;
				RemainingCount = remainingCount;
				FailedExports = failedExports;
			}
		}

		/// <summary>What CheatEngine.SDK reported for one registration, copied; only the lease stays an SDK object.</summary>
		internal readonly struct CheatEngineLuaPublication
		{
			internal readonly global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind Kind;
			internal readonly object? Lease;
			internal readonly string? FailedExport;
			internal readonly string? FailedStatus;
			internal readonly CheatEngineLuaRelease Rollback;

			internal CheatEngineLuaPublication(global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResultKind kind,
				object? lease, string? failedExport, string? failedStatus, CheatEngineLuaRelease rollback)
			{
				Kind = kind;
				Lease = lease;
				FailedExport = failedExport;
				FailedStatus = failedStatus;
				Rollback = rollback;
			}
		}

		""";

	/// <summary>The CheatEngine.SDK adapter; constant text, and the only generated code that calls the SDK.</summary>
	internal const string AdapterSource =
		"""
		// <auto-generated />
		#nullable enable

		namespace CheatEngine.Client.Lua.Generated;

		/// <summary>
		///     The only generated code that calls CheatEngine.SDK. Each member is one SDK call: the Lua admission and the end
		///     of the admitted operation, the SDK-generated registration of a module, and the release of a registration
		///     lease. It copies every result into Client-owned values and takes no decision;
		///     <see cref="CheatEngineLuaModuleRegistrar" /> does.
		/// </summary>
		internal static class CheatEngineLuaRegistrationAdapter
		{
			/// <summary>
			///     Asks CheatEngine.SDK to admit one Lua operation on this thread. When it is admitted,
			///     <paramref name="operation" /> holds it until <see cref="EndOperation" /> and <paramref name="state" /> is its
			///     state; otherwise nothing is held.
			/// </summary>
			internal static global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus TryAdmit(
				out global::CheatEngine.SDK.Lua.Runtime.LuaRuntimeOperation operation,
				out global::CheatEngine.SDK.Lua.State.LuaState state)
			{
				global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus admission =
					global::CheatEngine.SDK.Lua.Runtime.LuaRuntime.TryAcquireOperationWithOutcome(out operation);
				state = admission == global::CheatEngine.SDK.Lua.Runtime.LuaAdmissionStatus.Admitted
					? operation.State
					: default;
				return admission;
			}

			/// <summary>Ends an admitted operation before control returns to Cheat Engine.</summary>
			internal static void EndOperation(ref global::CheatEngine.SDK.Lua.Runtime.LuaRuntimeOperation operation)
			{
				operation.Dispose();
			}

			/// <summary>Runs the module's SDK-generated registration with the state of an admitted operation.</summary>
			internal static CheatEngineLuaPublication Publish(
				global::System.Func<global::CheatEngine.SDK.Lua.State.LuaState, global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResult> publish,
				global::CheatEngine.SDK.Lua.State.LuaState state)
			{
				global::CheatEngine.SDK.Lua.Registration.LuaRegistrationResult result = publish(state);
				global::CheatEngine.SDK.Lua.Registration.LuaRegistrationFailure? failure = result.Failure;
				return new CheatEngineLuaPublication(result.Kind, result.Lease,
					failure.HasValue ? failure.GetValueOrDefault().Name : null,
					failure.HasValue ? failure.GetValueOrDefault().LuaStatus.ToString() : null,
					Copy(result.Rollback));
			}

			/// <summary>Releases a registration lease with the state of an admitted operation.</summary>
			internal static CheatEngineLuaRelease Release(object lease, global::CheatEngine.SDK.Lua.State.LuaState state)
			{
				return Copy(((global::CheatEngine.SDK.Lua.Registration.LuaRegistrationLease) lease).ReleaseWithOutcome(state));
			}

			/// <summary>Consumes a registration lease without a Lua state; CheatEngine.SDK reports it stale.</summary>
			internal static CheatEngineLuaRelease ReleaseStale(object lease)
			{
				return Copy(((global::CheatEngine.SDK.Lua.Registration.LuaRegistrationLease) lease).ReleaseWithOutcome());
			}

			private static CheatEngineLuaRelease Copy(global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseOutcome outcome)
			{
				global::System.Collections.Generic.IReadOnlyList<global::CheatEngine.SDK.Lua.Registration.LuaRegistrationReleaseFailure> failures =
					outcome.Failures;
				string[] failed = new string[failures.Count];
				for (int index = 0; index < failed.Length; index++)
				{
					failed[index] = failures[index].Name;
				}

				return new CheatEngineLuaRelease(outcome.Kind, outcome.RemovedCount, outcome.RestoredCount,
					outcome.ReplacementCount, outcome.RemainingCount, failed);
			}
		}

		""";
}
