using System.Text;

namespace CheatEngine.Client.SourceGenerators.Lua;

/// <summary>Tab-indented text writer for generated C# sources.</summary>
internal sealed class SourceBuilder
{
	private readonly StringBuilder _source = new();
	private int _indent;

	public void WriteGeneratedHeader()
	{
		WriteLine("// <auto-generated />");
		WriteLine("#nullable enable");
		WriteLine();
	}

	public void OpenNamespace(string @namespace)
	{
		if (string.IsNullOrEmpty(@namespace))
		{
			return;
		}

		WriteLine("namespace " + @namespace + ";");
		WriteLine();
	}

	public void OpenBlock()
	{
		WriteLine("{");
		Indent();
	}

	public void CloseBlock()
	{
		Unindent();
		WriteLine("}");
	}

	public void WriteLine(string value = "")
	{
		if (value.Length != 0)
		{
			_source.Append('\t', _indent);
		}

		_source.AppendLine(value);
	}

	public void Indent()
	{
		_indent++;
	}

	public void Unindent()
	{
		_indent--;
	}

	public override string ToString()
	{
		return _source.ToString();
	}
}
