using System.Globalization;
using System.Reflection;

using CheatEngine.Client.Extensions.DependencyInjection;
using CheatEngine.Client.SourceGenerators.Lua.Tests.Infrastructure;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.Extensions.DependencyInjection;

namespace CheatEngine.Client.SourceGenerators.Lua.Tests;

public sealed class CheatEngineLuaGeneratorTests
{
	private const string ModuleSource = ModulePrefix +
	                                    """
	                                    [CheatEngineLuaModule(typeof(PluginLuaBindings), "plugin")]
	                                    internal sealed partial class PluginLuaModule : ILuaModule;
	                                    """;

	private const string ModulePrefix =
		"""
		using CheatEngine.Client.Lua;
		using CheatEngine.SDK.Annotations.Lua;
		namespace TestPlugin;
		internal static partial class PluginLuaBindings
		{
			[LuaFunction("status")]
			public static string Status() => "ok";

			[LuaFunction("ping")]
			public static int Ping() => 1;
		}
		""";

	private const string ScalarOperationSource =
		"""
		using CheatEngine.Client.Lua;
		using CheatEngine.SDK.Annotations.Lua;
		namespace TestPlugin;
		internal static partial class Globals
		{
			[CheatEngineLuaOperation]
			[LuaGlobal("getVersion")]
			public static partial int ReadVersion(int address);
		}
		""";

	private const string OutResultOperationSource =
		"""
		using CheatEngine.Client.Lua;
		using CheatEngine.SDK.Annotations.Lua;
		namespace TestPlugin;
		internal static partial class Globals
		{
			[CheatEngineLuaOperation]
			[LuaGlobal("getVersion")]
			public static partial bool TryReadVersion(int address, out int version);
		}
		""";

	private const string ModuleCompilationSource =
		"""
		using CheatEngine.Client.Lua;
		using CheatEngine.SDK.Annotations.Lua;
		using CheatEngine.SDK.Lua.Calls;
		using CheatEngine.SDK.Lua.State;
		namespace TestPlugin;
		internal static partial class PluginLuaBindings
		{
			[LuaFunction("status")]
			public static string Status() => "ok";

			public static LuaStatus RegisterLuaFunctions(LuaState state) => default;
			public static LuaStatus UnregisterLuaFunctions(LuaState state) => default;
		}

		[CheatEngineLuaModule(typeof(PluginLuaBindings), "plugin")]
		internal sealed partial class PluginLuaModule : ILuaModule;
		""";

	private const string MappedOperationSource =
		"""
		using CheatEngine.Client.Lua;
		using CheatEngine.SDK.Annotations.Lua;
		namespace TestPlugin;
		internal sealed class SdkSnapshot
		{
		}

		internal readonly record struct Snapshot(int Value);

		internal readonly struct SnapshotMapper : ILuaResultMapper<SdkSnapshot, Snapshot>
		{
			public static Snapshot Map(SdkSnapshot source) => new(0);
		}

		internal static partial class Globals
		{
			[CheatEngineLuaOperation(typeof(SnapshotMapper))]
			[LuaGlobal("getSnapshot")]
			public static partial SdkSnapshot ReadSnapshot();
		}
		""";

	private static readonly string[] InvalidModuleDiagnosticIds = ["CECLUA1001", "CECLUA1005"];

	[Fact]
	public void ModuleAdapterSnapshotUsesOneAdmittedOperationAndPreflightsEveryExport()
	{
		GeneratorRun run = GeneratorRun.Execute(ModuleSource);

		Assert.Empty(run.Diagnostics);
		string generated = run.GeneratedText("PluginLuaModule.CheatEngineLuaModule.g.cs");
		Assert.Equal(
			"""
			// <auto-generated />
			#nullable enable

			namespace TestPlugin;

			internal partial class PluginLuaModule : global::CheatEngine.Client.Lua.IDescribedLuaModule
			{
				/// <summary>Initializes a Lua module instance for activation-scoped dependency injection.</summary>
				public PluginLuaModule()
				{
				}

				private static readonly global::CheatEngine.Client.Lua.LuaModuleDescriptor s_descriptor =
					new global::CheatEngine.Client.Lua.LuaModuleDescriptor(
						"plugin",
						global::System.Collections.Immutable.ImmutableArray.Create(new global::CheatEngine.Client.Lua.LuaExportDescriptor("status"), new global::CheatEngine.Client.Lua.LuaExportDescriptor("ping")));

			""" + "\n",
			NormalizeLineEndings(generated[..generated.IndexOf("\t/// <inheritdoc />", StringComparison.Ordinal)]));
		Assert.Equal(2, Count(generated, "LuaRuntime.AcquireOperation()"));
		Assert.Contains("EnsureExportsAreVacant(operation.State);", generated, StringComparison.Ordinal);
		Assert.Contains("state.TryGetGlobal(\"status\"u8)", generated, StringComparison.Ordinal);
		Assert.Contains("state.TryGetGlobal(\"ping\"u8)", generated, StringComparison.Ordinal);
		Assert.Contains(
			"finally\n\t\t{\n\t\t\t_ = global::TestPlugin.PluginLuaBindings.UnregisterLuaFunctions(operation.State);",
			NormalizeLineEndings(generated), StringComparison.Ordinal);
	}

	[Fact]
	public void ModuleAdapterCompilesAgainstTheSdkRegistrationContract()
	{
		GeneratorRun run = GeneratorRun.Execute(ModuleCompilationSource);

		Diagnostic[] diagnostics =
		[
			.. run.OutputCompilation.GetDiagnostics(TestContext.Current.CancellationToken)
				.Where(static diagnostic => diagnostic.Severity >= DiagnosticSeverity.Warning)
		];
		Assert.Empty(diagnostics);
	}

	[Fact]
	public void GeneratedInternalModuleHasAPublicConstructorAndResolvesViaAddLuaModule()
	{
		GeneratorRun run = GeneratorRun.Execute(ModuleCompilationSource);
		Assert.Empty(run.Diagnostics);
		Assert.Contains("public PluginLuaModule()", run.GeneratedText("PluginLuaModule.CheatEngineLuaModule.g.cs"),
			StringComparison.Ordinal);

		using MemoryStream image = new();
		EmitResult emitResult =
			run.OutputCompilation.Emit(image, cancellationToken: TestContext.Current.CancellationToken);
		Assert.True(emitResult.Success, string.Join(Environment.NewLine, emitResult.Diagnostics));
		System.Reflection.Assembly generatedAssembly = System.Reflection.Assembly.Load(image.ToArray());
		Type? discoveredModuleType = generatedAssembly.GetType("TestPlugin.PluginLuaModule", false);
		Assert.NotNull(discoveredModuleType);
		Type moduleType = discoveredModuleType!;
		Assert.False(moduleType.IsPublic);
		Assert.NotNull(moduleType.GetConstructor(BindingFlags.Instance | BindingFlags.Public, null,
			Type.EmptyTypes, null));

		ServiceCollection services = new();
		CheatEngineClientBuilder builder = services.AddCheatEngineClient();
		MethodInfo addLuaModule = Assert.Single(
			typeof(CheatEngineClientBuilder).GetMethods(BindingFlags.Instance | BindingFlags.Public),
			static method => method.Name == nameof(CheatEngineClientBuilder.AddLuaModule) &&
			                 method.IsGenericMethodDefinition);
		Assert.Same(builder, addLuaModule.MakeGenericMethod(moduleType).Invoke(builder, null));

		using ServiceProvider provider = services.BuildServiceProvider();
		object module = provider.GetRequiredService(moduleType);
		Assert.Equal(moduleType, module.GetType());
	}

	[Fact]
	public void ExplicitPublicConstructorIsPreservedForDependencyInjection()
	{
		GeneratorRun run = GeneratorRun.Execute(ModulePrefix +
		                                        """
		                                        public sealed class ModuleDependency;

		                                        [CheatEngineLuaModule(typeof(PluginLuaBindings), "plugin")]
		                                        internal sealed partial class PluginLuaModule : ILuaModule
		                                        {
		                                            public PluginLuaModule(ModuleDependency dependency)
		                                            {
		                                            }
		                                        }
		                                        """);

		Assert.Empty(run.Diagnostics);
		string generated = run.GeneratedText("PluginLuaModule.CheatEngineLuaModule.g.cs");
		Assert.DoesNotContain("public PluginLuaModule()", generated, StringComparison.Ordinal);
	}

	[Fact]
	public void OnlyNonPublicExplicitConstructorsProduceAnActionableDiagnostic()
	{
		GeneratorRun run = GeneratorRun.Execute(ModulePrefix +
		                                        """
		                                        [CheatEngineLuaModule(typeof(PluginLuaBindings), "plugin")]
		                                        internal sealed partial class PluginLuaModule : ILuaModule
		                                        {
		                                            internal PluginLuaModule()
		                                            {
		                                            }
		                                        }
		                                        """);

		Assert.Contains(run.Diagnostics, static diagnostic => diagnostic.Id == "CECLUA1006");
		Assert.Empty(run.GeneratedSources);
	}

	[Fact]
	public void ScalarOperationAdapterEmitsAReadonlyValueAndTypedFactory()
	{
		GeneratorRun run = GeneratorRun.Execute(ScalarOperationSource);

		Assert.Empty(run.Diagnostics);
		string generated = run.GeneratedText("ReadVersion.CheatEngineLuaOperation.g.cs");
		Assert.Contains(
			"public static ReadVersionLuaOperation CreateReadVersionLuaOperation(global::System.Int32 address)",
			generated, StringComparison.Ordinal);
		Assert.Contains("internal readonly record struct ReadVersionLuaOperation(global::System.Int32 _address)",
			generated, StringComparison.Ordinal);
		Assert.Contains("global::TestPlugin.Globals.ReadVersion(_address)", generated, StringComparison.Ordinal);
		Assert.Contains("CheatEngineFailureKind.LuaError", generated, StringComparison.Ordinal);
		Assert.DoesNotContain("LuaState", generated, StringComparison.Ordinal);
		Assert.DoesNotContain("LuaRef", generated, StringComparison.Ordinal);
	}

	[Fact]
	public void OutResultOperationProjectsTheSingleSdkOutValueAndMapsFalseToAFailure()
	{
		GeneratorRun run = GeneratorRun.Execute(OutResultOperationSource);

		Assert.Empty(run.Diagnostics);
		string generated = run.GeneratedText("TryReadVersion.CheatEngineLuaOperation.g.cs");
		Assert.Contains("global::System.Int32 source;", generated, StringComparison.Ordinal);
		Assert.Contains("if (!global::TestPlugin.Globals.TryReadVersion(_address, out source))", generated,
			StringComparison.Ordinal);
		Assert.Contains("CheatEngineFailureKind.LuaError", generated, StringComparison.Ordinal);
		Assert.Contains("result = source;", generated, StringComparison.Ordinal);
	}

	[Fact]
	public void MappedOperationUsesTheDeclaredStaticMapperAndProjectsTheResultType()
	{
		GeneratorRun run = GeneratorRun.Execute(MappedOperationSource);

		Assert.Empty(run.Diagnostics);
		string generated = run.GeneratedText("ReadSnapshot.CheatEngineLuaOperation.g.cs");
		Assert.Contains("ILuaOperation<global::TestPlugin.Snapshot>", generated, StringComparison.Ordinal);
		Assert.Contains("global::TestPlugin.SnapshotMapper.Map(source)", generated, StringComparison.Ordinal);
	}

	[Theory]
	[InlineData(
		"[CheatEngineLuaModule(typeof(PluginLuaBindings), \" \")] internal sealed partial class PluginLuaModule { }")]
	[InlineData(
		"[CheatEngineLuaModule(typeof(PluginLuaBindings), \"plugin\")] internal sealed class PluginLuaModule { }")]
	public void InvalidModuleFormsProduceActionableDiagnostics(string moduleDeclaration)
	{
		GeneratorRun run = GeneratorRun.Execute(ModulePrefix + moduleDeclaration);

		Diagnostic diagnostic =
			Assert.Single(run.Diagnostics.Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
		Assert.Contains(diagnostic.Id, InvalidModuleDiagnosticIds);
		Assert.Empty(run.GeneratedSources);
	}

	[Fact]
	public void DuplicateModuleExportsProduceAnActionableDiagnostic()
	{
		GeneratorRun run = GeneratorRun.Execute(
			"""
			using CheatEngine.Client.Lua;
			using CheatEngine.SDK.Annotations.Lua;
			namespace TestPlugin;
			internal static partial class PluginLuaBindings
			{
				[LuaFunction("status")]
				public static string First() => "first";

				[LuaFunction("status")]
				public static string Second() => "second";
			}

			[CheatEngineLuaModule(typeof(PluginLuaBindings), "plugin")]
			internal sealed partial class PluginLuaModule
			{
			}
			""");

		Diagnostic diagnostic =
			Assert.Single(run.Diagnostics.Where(static diagnostic => diagnostic.Id == "CECLUA1004"));
		Assert.Contains("duplicate", diagnostic.GetMessage(CultureInfo.InvariantCulture),
			StringComparison.OrdinalIgnoreCase);
		Assert.Empty(run.GeneratedSources);
	}

	[Fact]
	public void OperationWithoutLuaGlobalProducesAnActionableDiagnostic()
	{
		GeneratorRun run = GeneratorRun.Execute(
			"""
			using CheatEngine.Client.Lua;
			namespace TestPlugin;
			internal static partial class Globals
			{
				[CheatEngineLuaOperation]
				public static partial int ReadVersion();
			}
			""");

		Diagnostic diagnostic =
			Assert.Single(run.Diagnostics.Where(static diagnostic => diagnostic.Id == "CECLUA1101"));
		Assert.Contains("[LuaGlobal]", diagnostic.GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
	}

	[Fact]
	public void MapperCannotReturnRawLuaStateAcrossTheClientBoundary()
	{
		GeneratorRun run = GeneratorRun.Execute(
			"""
			using CheatEngine.Client.Lua;
			using CheatEngine.SDK.Annotations.Lua;
			using CheatEngine.SDK.Lua.State;
			namespace TestPlugin;
			internal readonly struct UnsafeMapper : ILuaResultMapper<LuaState, LuaState>
			{
				public static LuaState Map(LuaState source) => source;
			}

			internal static partial class Globals
			{
				[CheatEngineLuaOperation(typeof(UnsafeMapper))]
				[LuaGlobal("unsafe")]
				public static partial LuaState GetUnsafe();
			}
			""");

		Assert.Contains(run.Diagnostics, static diagnostic => diagnostic.Id == "CECLUA1106");
		Assert.Empty(run.GeneratedSources);
	}

	[Fact]
	public void UnchangedInputReusesTheIncrementalOutput()
	{
		GeneratorRun first = GeneratorRun.Execute(ModuleSource);
		Compilation unchangedCompilation = first.OutputCompilation.RemoveAllSyntaxTrees()
			.AddSyntaxTrees(CSharpSyntaxTree.ParseText(ModuleSource,
				cancellationToken: TestContext.Current.CancellationToken));
		GeneratorRun second = GeneratorRun.Execute(first.Driver, unchangedCompilation);

		Assert.Empty(second.Diagnostics);
		Assert.Equal(first.GeneratedSources.Select(static source => source.SourceText.ToString()),
			second.GeneratedSources.Select(static source => source.SourceText.ToString()));
		GeneratorRunResult result = Assert.Single(second.Result.Results);
		Assert.NotEmpty(result.TrackedSteps);
	}

	private static int Count(string value, string fragment)
	{
		int count = 0;
		int start = 0;
		while ((start = value.IndexOf(fragment, start, StringComparison.Ordinal)) >= 0)
		{
			count++;
			start += fragment.Length;
		}

		return count;
	}

	private static string NormalizeLineEndings(string value)
	{
		return value.Replace("\r\n", "\n", StringComparison.Ordinal);
	}
}
