<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../libs/CheatEngine.Client.Abstractions/CheatEngine.Client.Abstractions.csproj"/>
    <ProjectReference Include="../../libs/CheatEngine.Client.Binding/CheatEngine.Client.Binding.csproj"/>
    <ProjectReference Include="../../libs/CheatEngine.Client.Fluent/CheatEngine.Client.Fluent.csproj"/>
  </ItemGroup>

</Project>
